#!/bin/bash
# Point to the directory containing main.go
GOOS=darwin GOARCH=arm64 go build -o tuiwall ./cmd/tuiwall
# OR if your files are in the root:
# GOOS=darwin GOARCH=arm64 go build -o tuiwall .

sudo cp tuiwall /opt/homebrew/bin/
